title: Tic Tac Toe Evaluator
description: Evaluate Tic Tac Toe images using deep learning
about:


  This is Tic-Tac-Toe Evaluator built on top of a Food Images Classifier 
  using Deep Learning built on top of Pytorch. It was built by [Ian Leong] (https://github.com/ianpaulleong)


  The Food Classifier project was built by 
  [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).

  



  More info and the source code can be found below.


  - [Tic Tac Toe code] https://github.com/ianpaulleong/TicTacToeApp


  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    

  - [Web app](https://food-img-classifier.herokuapp.com)

  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)


code: https://github.com/ianpaulleong/TicTacToeApp

sampleImages:
  - name: Sample 1
    url: https://ecdn.teacherspayteachers.com/thumbitem/Tic-Tac-Toe-Game-4129207-1539893104/original-4129207-1.jpg
  - name: Sample 2
    url: https://www.cdn.geeksforgeeks.org/wp-content/uploads/tic_tac_toe.jpg
  - name: Sample 3
    url: https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX2840770.jpg
  - name: Sample 4
    url: http://thetechnicgear.com/wp-content/uploads/2013/05/tic_tac_toe.png
  - name: Sample 5
    url: https://cdn3.vectorstock.com/i/1000x1000/92/52/tic-tac-toe-hand-drawn-game-on-a-white-vector-28329252.jpg
  - name: Sample 6
    url: https://cdn.pixabay.com/photo/2015/09/17/15/44/game-944386_960_720.jpg
