title: Tic Tac Toe Evaluator
description: Evaluate Tic Tac Toe images using deep learning
about:


  This is Tic-Tac-Toe Evaluator built on top of a Food Images Classifier 
  using Deep Learning built on top of Pytorch. It was built by [Ian Leong] (https://github.com/ianpaulleong)


  The Food Classifier project was built by 
  [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).

  



  More info and the source code can be found below.


  - [Tic Tac Toe code] https://github.com/ianpaulleong/TicTacToeApp


  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    

  - [Web app](https://food-img-classifier.herokuapp.com)

  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)


code: https://github.com/ianpaulleong/TicTacToeApp

sampleImages:
  - name: Sample 1
    url: https://previews.123rf.com/images/lprising/lprising1607/lprising160700001/61316396-a-hand-drawn-tic-tac-toe-game-grid.jpg
  - name: Sample 2
    url: https://thumbs.dreamstime.com/z/tic-tac-toe-vector-icon-hand-drawing-game-play-drawn-143732664.jpg
